services:
  db:
    image: postgres:latest
    container_name: postgres_prod
    restart: always
    environment:
      POSTGRES_DB: mydatabase_dev
      POSTGRES_USER: SA
      POSTGRES_PASSWORD: Pi3141592654!
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  pgdata:

